config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  controller :nutri do
    get "nutri/buscar_produto" => :buscar_produto
    get "nutri/calcula_correspondencias" => :calcula_correspondencias
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  has_one :nutritional_content, dependent: :destroy

  enum category: {
    carbohydrates: 0,
    protein: 1,
    fat: 2
  }

  after_create :add_category

  private

  def add_category
    macros = self.nutritional_content.slice('fat', 'carbohydrates', 'protein')
    self.category = macros.key(macros.values.max)
    self.save
  rescue
    puts "$$$$$$$$$$$$$$$$$$ ERRO AO ADICIONAR CATEGORIA ITEM #{self.id} $$$$$$$$$$$$$$$$$$"
  end
end

app/models/nutri_spider.rb
class NutriSpider < Kimurai::Base
  @name = "nutri_items_spider"
  @engine = :mechanize
  @start_urls = []
  @config = {
    user_agent: "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.84 Safari/537.36",
    before_request: { delay: 4..7 }
  }

  def parse(response, url:, data: {})
    js = response.search("script").text[/\items\":(.*?),\"totalResultsCount\":/,1]
    items = JSON.parse(js)
    items_parse = []

    items.each do |item|
      params_item = {
        name: item.dig("item", "brand_name"),
        description: item.dig("item", "description"),
        verified: item.dig("item", "verified")
      }
      novo_item = Item.find_or_initialize_by(params_item)
      if novo_item.id.blank?
        novo_item = Item.new(params_item)
        nutritional = NutritionalContent.new
        nutritional.portion = item.dig("item", "serving_sizes", 0, "value") || 0
        nutritional.unit_g_multiplier = item.dig("item", "serving_sizes", 1, "nutrition_multiplier") || 0
        nutritional.unit = item.dig("item", "nutritional_contents", "energy", "unit") || 0
        nutritional.calories = item.dig("item", "nutritional_contents", "energy", "value") || 0
        nutritional.calcium = item.dig("item", "nutritional_contents", "calcium") || 0
        nutritional.carbohydrates = item.dig("item", "nutritional_contents", "carbohydrates") || 0
        nutritional.cholesterol = item.dig("item", "nutritional_contents", "cholesterol") || 0
        nutritional.fat = item.dig("item", "nutritional_contents", "fat") || 0
        nutritional.fiber = item.dig("item", "nutritional_contents", "fiber") || 0
        nutritional.iron = item.dig("item", "nutritional_contents", "iron") || 0
        nutritional.monounsaturated_fat = item.dig("item", "nutritional_contents", "monounsaturated_fat") || 0
        nutritional.polyunsaturated_fat = item.dig("item", "nutritional_contents","polyunsaturated_fat") || 0
        nutritional.potassium = item.dig("item", "nutritional_contents", "potassium") || 0
        nutritional.protein = item.dig("item", "nutritional_contents", "protein") || 0
        nutritional.saturated_fat = item.dig("item", "nutritional_contents", "saturated_fat") || 0
        nutritional.sodium = item.dig("item", "nutritional_contents", "sodium") || 0
        nutritional.sugar = item.dig("item", "nutritional_contents", "sugar") || 0
        nutritional.trans_fat = item.dig("item", "nutritional_contents", "trans_fat") || 0
        nutritional.vitamin_a = item.dig("item", "nutritional_contents", "vitamin_a") || 0
        nutritional.vitamin_c = item.dig("item", "nutritional_contents", "vitamin_c") || 0

        novo_item.nutritional_content = nutritional
        novo_item.save
      end
      items_parse << novo_item
    end

    return items_parse
  end
end

app/models/nutritional_content.rb
class NutritionalContent < ApplicationRecord
  belongs_to :item
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @produtos = params[:produtos] unless params[:produtos].blank?
  end
end

app/controllers/nutri_controller.rb
class NutriController < ApplicationController
  def buscar_produto
    if params[:produto_1]
      termo = params[:produto_1]
      @product = "produto_1"
    elsif params[:produto_2]
      termo = params[:produto_2]
      @product = "produto_2"
    else
      @product = ""
    end

    @items = []
    2.times do |pg|
      url = "https://www.myfitnesspal.com/pt/food/search?page=#{pg+1}&search=#{termo}"
      @items += NutriSpiderService.parse!(:parse, url: url)
    end


    if response[:status] == :completed && response[:error].nil?
      p "Successfully scraped url"
    else
      p response[:error]
    end

    respond_to do |format|
      format.html { redirect_to root_path }
      format.js
    end

  rescue StandardError => e
    flash.now[:alert] = "Error: #{e}"
  end

  def calcula_correspondencias

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/nutri_helper.rb
module NutriHelper
end

app/views/home/index.html.erb
<h1>Home</h1>

<%= form_with url: nutri_buscar_produto_path, method: :get, local: false do |form| %>
  <div style="margin-bottom: 10px;">
    <label for="produto_1">Produto 1</label>
    <%= form.text_field :produto_1, required: true %>
    <%= form.submit "buscar" %>
  </div>
<% end %>
<div id="produto_1_results"></div>

<%= form_with url: nutri_buscar_produto_path, method: :get, local: false do |form| %>
  <div style="margin-bottom: 10px;">
    <label for="produto_2">Produto 2</label>
    <%= form.text_field :produto_2, required: true %>
    <%= form.submit "buscar" %>
  </div>
<% end %>
<div id="produto_2_results"></div>

<% unless @produtos.blank? %>
  <%= @produtos %>
<% end %>

<script type="text/javascript">
  $(function() {
    sessionStorage.removeItem("produto_1");
    sessionStorage.removeItem('produto_2');
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MacronutriCalculadora</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js', 'data-turbolinks-track': 'reload'%>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload'%>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/nutri/_items_list.html.erb
<div class="border">
  <% if items.blank? %>
    Nenhum Resultado
  <% else %>
    <% items.each do |item| %>
      <div class="<%= @product %>" id="<%= item.id %>" style="margin-bottom: 10px">
        <span>Nome: <%= item.name %></span> |
        <span>Descrição: <%= item.description %></span>
        <button>detalhes</button>
        <br><strong>Resumo:</strong><br>
        <span>Carbo: <%= item.nutritional_content.carbohydrates %></span> |
        <span>Gordura: <%= item.nutritional_content.fat %></span> |
        <span>Proteina: <%= item.nutritional_content.protein %></span>
      </div>
    <% end %>
  <% end %>
</div>

app/views/nutri/buscar_produto.js.erb
$("#<%=@product%>_results").html('<%= j render "/nutri/items_list", items: @items, product: @product %>');

$(function seleciona(){
  $(".<%= @product %>").click(function(){
    sessionStorage.setItem("<%= @product %>", $(this).attr('id'));
    if(sessionStorage.getItem("produto_1") && sessionStorage.getItem("produto_2")){
      alert("Tudo certo!");
    };
  });
});